---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    appid: "1111"

spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        appid: "1111"
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
  replicas: 3
