---
apiVersion: v1
kind: Secret
metadata:
  name: webapp-secrets
data:
  secret1: c3VwZXItc2VjcmV0LXZhbHVlMQo=


---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: web
        image: nginx:latest
        ports:
        - containerPort: 80
        envFrom:
          - secretRef: 
             name: webapp-secrets

      - name: db
        image: mongo:latest